### ISSUE TITLE
Better Documentation for Shortcode Usage

### ISSUE THREAD

**Issue by buschschwick** [factor1/Prelude#15]
Documentation for shortcode maker is out of date and needs updated with `[fluidvideo]` instructions.

**Comment by buschschwick** [comment]
Added '[fluidvideo]' instructions with commit https://github.com/factor1/factor1_blankwp/commit/552ae03775a1eefacd7d0e8ec2b0fe72765f057a 

For the `2.1.0` milestone, this is all I'm going to mark off - but going to mark it help wanted because I'm sure these could be improved.

**Comment by buschschwick** [comment]
@mattada you had more insight into how these shortcodes worked, if you feel your interest peaked, maybe you could improve upon that documentation?

**Comment by buschschwick** [comment]
@mattada would there be a good time for @bebaps to bust some of these out in the near future? I know he had expressed interest in doing so, and he may have already started.

@bebaps if you want to create a new branch `shortcode-instructions` and make those changes and I can roll them into the next release(s).

**Comment by bebaps** [comment]
@buschschwick I can look into this again, but honestly I have only used this one time, for one shortcode. Even in the projects I have touched just for maintenance I think only one utilized the shortcodes.

I initially had kind of an all or nothing mindset about it, to either make a robust set of shortcodes that allowed our clients to utilize Foundation to the fullest, or just to scrap it since it appears it just isn't being used anyway. Lately I have just been removing it altogether, and since no one has noticed I think I am on the right track with that so far.

**Comment by mattada** [comment]
Yeah, im leaning toward dropping them. They are super buggy and not used as much as they once were. Im open to a full revamp of them, but for now maybe we drop them from prelude.

**Comment by buschschwick** [comment]
The only ones I tend to use are `flex-video` and custom `button` ones. I'm okay with removing most of the ones that are layout based for sure but I don't think I'd want to get rid the ability to easily create them when needed.

**Comment by mattada** [comment]
I think the key on the video or buttons, would be to save the functions in our yet to be determined code snippet repo for use as needed. If we are thinking larger base of use here, we dont want to include too much secrete sauce with the shortcode maker on the whole, and i dont really want to document how it works too much

**Comment by buschschwick** [comment]
Shortcodes will be destroyed in `2.2.0` 💣
